/* This file is generated by Payload */
import config from '@/payload.config'
import { NotFoundPage } from '@payloadcms/next/views'
import { importMap } from '../importMap'

type Args = {
  params: Promise<{
    payload?: string[]
  }>
  searchParams: Promise<{
    [key: string]: string | string[]
  }>
}

const Page = ({ params, searchParams }: Args) =>
  NotFoundPage({
    config,
    importMap,
    params: params.then(({ payload = [] }) => ({ segments: payload })),
    searchParams,
  })

export default Page
